<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFrameworks>netcoreapp3.0;netstandard2.0;netstandard1.6;net451</TargetFrameworks>
    <NeutralLanguage>en-US</NeutralLanguage>
    <Description>Lê e grava CSV, tamanho fixo e outros formatos de arquivo simples com foco na definição, configuração e velocidade do esquema. Suporta mapeamento diretamente entre arquivos e classes.</Description>
    <Copyright>Copyright @ 2021</Copyright>
    <PackageLicenseUrl></PackageLicenseUrl>
    <PackageProjectUrl></PackageProjectUrl>
    <RepositoryUrl></RepositoryUrl>
    <RepositoryType></RepositoryType>
    <PackageTags>csv;comma;tab;separated;value;delimited;flat;file;fixed;width;fixed-width;length;fixed-length;parser;parsing;parse</PackageTags>
    <PackageReleaseNotes>O comportamento de "TypedWriter.WriteAll" é um tanto não intuitivo quando chamado sem registros. A expectativa é que o cabeçalho / esquema seja escrito ao executar essa operação em massa; caso contrário, o chamador terá que chamar explicitamente WriteSchema de antemão. Isso altera um pouco o comportamento do código, de modo que pode resultar em cabeçalhos / esquema sendo escritos nos casos em que o arquivo estava em branco antes. No entanto, quando IsFirstRecordSchema for true, é extremamente improvável que os consumidores esperem que um arquivo em branco seja gerado.

Durante o teste, descobriu um bug em que o esquema estava sendo configurado e, em seguida, desconfigurou quando o registro do cabeçalho / esquema era o único registro no arquivo. Deve ser capaz de tentar ler o primeiro registro de um arquivo vazio e obter falso de volta, então ler o esquema via GetSchema; no entanto, o código lançaria uma InvalidOperationException ou, pior, uma NullReferenceException.</PackageReleaseNotes>
    <SignAssembly>true</SignAssembly>
    <AssemblyOriginatorKeyFile>FlatFiles.snk</AssemblyOriginatorKeyFile>
    <Version>4.14.0</Version>
  </PropertyGroup>

  <PropertyGroup>
    <LangVersion>8.0</LangVersion>
    <PackageIconUrl></PackageIconUrl>
    <AssemblyVersion>4.14.0.0</AssemblyVersion>
    <FileVersion>4.14.0.0</FileVersion>
    <PackageLicenseFile>UNLICENSE.txt</PackageLicenseFile>
    <PackageIcon>icon.png</PackageIcon>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|netstandard1.6|AnyCPU'">
    <DocumentationFile>bin\Debug\netstandard1.6\FlatFiles.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|netstandard1.6|AnyCPU'">
    <DocumentationFile>bin\Release\netstandard1.6\FlatFiles.xml</DocumentationFile>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|netstandard2.0|AnyCPU'">
    <DocumentationFile>bin\Debug\netstandard2.0\FlatFiles.xml</DocumentationFile>
  </PropertyGroup>
  
  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|netstandard2.0|AnyCPU'">
    <DocumentationFile>bin\Release\netstandard2.0\FlatFiles.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|netcoreapp3.0|AnyCPU'">
    <DocumentationFile>bin\Debug\netcoreapp3.0\FlatFiles.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|netcoreapp3.0|AnyCPU'">
    <DocumentationFile>bin\Release\netcoreapp3.0\FlatFiles.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Debug|net451|AnyCPU'">
    <DocumentationFile>bin\Debug\net451\FlatFiles.xml</DocumentationFile>
  </PropertyGroup>

  <PropertyGroup Condition="'$(Configuration)|$(TargetFramework)|$(Platform)'=='Release|net451|AnyCPU'">
    <DocumentationFile>bin\Release\net451\FlatFiles.xml</DocumentationFile>
  </PropertyGroup>

  <ItemGroup>
    <Compile Update="Properties\Resources.Designer.cs">
      <DesignTime>True</DesignTime>
      <AutoGen>True</AutoGen>
      <DependentUpon>Resources.resx</DependentUpon>
    </Compile>
  </ItemGroup>

  <ItemGroup>
    <EmbeddedResource Update="Properties\Resources.resx">
      <Generator>ResXFileCodeGenerator</Generator>
      <LastGenOutput>Resources.Designer.cs</LastGenOutput>
    </EmbeddedResource>
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="System.ValueTuple" Version="4.5.0" />
    <PackageReference Include="System.Threading.Tasks.Extensions" Version="4.5.3" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='netstandard1.6'">
    <PackageReference Include="System.Reflection.Emit" Version="4.3.0" />
  </ItemGroup>
  
  <ItemGroup Condition="'$(TargetFramework)'=='netstandard2.0'">
    <PackageReference Include="System.Reflection.Emit" Version="4.6.0" />
    <PackageReference Include="System.Data.Common" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup Condition="'$(TargetFramework)'=='netcoreapp3.0'">
    <PackageReference Include="System.Reflection.Emit" Version="4.6.0" />
    <PackageReference Include="System.Data.Common" Version="4.3.0" />
  </ItemGroup>

  <ItemGroup>
    <None Include="..\icon.png">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
    <None Include="..\UNLICENSE.txt">
      <Pack>True</Pack>
      <PackagePath></PackagePath>
    </None>
  </ItemGroup>

</Project>
